// English dictionary — generated by merging per-page fragments.
// Keys mirror the other language exactly.
export const en = {
  "nav": {
    "home": "Home",
    "services": "Services",
    "contact": "Contact",
    "appointments": "Appointments",
    "openEnrollment": "Open Enrollment",
    "taxSeason": "Tax Season",
    "news": "News",
    "reviews": "Reviews",
    "switchToEnglish": "Switch to Spanish",
    "toggleTheme": "Toggle light/dark mode",
    "toggleNav": "Toggle navigation"
  },
  "footer": {
    "adminAccess": "Administrator access",
    "call": "Call",
    "email": "Email",
    "company": "Faby Services Insurance & Accounting",
    "designedBy": "Designed by"
  },
  "appointments": {
    "meta": {
      "title": "Appointments | Faby Services Insurance and Bookkeeping"
    },
    "heading": "Appointments",
    "intro": "Send us your request and we'll get in touch to confirm the date and time.",
    "form": {
      "name": "Full Name",
      "phone": "Phone",
      "preferredDateTime": "Preferred date and time",
      "message": "Message",
      "messagePlaceholder": "Tell us what type of service you need...",
      "submit": "Send",
      "reset": "Clear Form"
    },
    "countries": {
      "us": "United States",
      "mx": "Mexico",
      "sv": "El Salvador",
      "ni": "Nicaragua",
      "cr": "Costa Rica",
      "pa": "Panama",
      "co": "Colombia",
      "es": "Spain"
    },
    "email": {
      "subject": "Appointment Request",
      "intro": "New appointment request:",
      "name": "Name",
      "phone": "Phone",
      "preferred": "Preferred date/time",
      "notSpecified": "(not specified)",
      "message": "Message",
      "noMessage": "(no message)"
    }
  },
  "contact": {
    "meta": {
      "title": "Contact | Faby Services Insurance and Accounting"
    },
    "heading": "Contact Us",
    "intro": "Have questions? We're here to help.",
    "details": {
      "phoneLabel": "Phone:",
      "emailLabel": "Email:",
      "locationLabel": "Location:"
    },
    "cta": "Prefer to speak in person? Call us or visit us during business hours.",
    "mapAria": "Open maps"
  },
  "home": {
    "meta": {
      "title": "Home | Faby Services"
    },
    "hero": {
      "title": "Trusted Tax Services and Business Consulting",
      "p1": "At Faby Services, we help individuals, families, and small businesses take control of their finances with clarity, confidence, and compassion. We understand that handling taxes, insurance, and document preparation can be overwhelming—especially when you try to do it on your own. That's why we've built our services around one simple idea: personalized, honest support you can rely on.",
      "p2": "We approach every client with care and intention. Whether you're filing taxes for the first time, securing a health plan for your family, or managing your small business finances, we listen closely to your needs and guide you through every detail. No confusing jargon. No rushed explanations. Just clear, practical guidance tailored to your situation.",
      "p3": "Our team is deeply rooted in the community we serve. Many of our clients come to us through referrals—from neighbors, friends, and family members who trust us to deliver results. We take that trust very seriously. That's why we go the extra mile to make sure every form is accurate, every deadline is met, and every question receives a thoughtful answer.",
      "p4": "Beyond the paperwork, we're here to advocate for your financial well-being. We stay up to date with changes in tax laws, health coverage options, and compliance requirements, so you don't have to. Our goal is to make sure you not only meet your obligations, but also seize opportunities—saving money where you can and protecting what matters most.",
      "p5": "When you work with Faby Services, you're not just hiring a tax preparer or an insurance specialist. You're gaining a partner committed to your long-term stability and success. Whatever stage of life you're in or challenges you face—we're here to support you every step of the way."
    },
    "mission": {
      "title": "Empowering Your Finances, Securing Your Future",
      "p1": "At Faby Services, we specialize in providing clear, reliable support across a range of financial and administrative services, including accounting advice, tax preparation, and the processing of official documents. Whether you're an individual planning for the year ahead or a small business facing complex obligations, we offer the expertise and structure you need to move forward with confidence.",
      "p2": "Our approach is grounded in simplicity and integrity. We believe everyone deserves access to sound financial planning—without intimidation, confusion, or hidden fees. That's why we take the time to explain your options, help you make informed decisions, and ensure your documents are accurate and compliant at every step of the process.",
      "p3": "We know that financial stress doesn't just affect your wallet—it also impacts your peace of mind, your ability to plan for the future, and the well-being of your family. Our mission is to remove that stress by becoming a trusted, knowledgeable partner you can count on year after year. Whether it's tax season, open enrollment, or time to register a business, we're here to guide you.",
      "p4": "Health coverage is another pillar of our support. Many clients come to us not knowing where to begin or overwhelmed by the enrollment process. We simplify that path, helping you find and secure the best possible insurance for your circumstances. Because financial security isn't just about numbers—it includes the peace of mind of knowing your health and your future are protected.",
      "p5": "At Faby Services, empowerment isn't just a buzzword—it's our commitment. We're here to help you take control of your finances, understand your rights and responsibilities, and take confident steps toward a more stable future. No matter your background or situation, we welcome you with respect, clarity, and genuine care."
    },
    "beliefs": {
      "title": "What We Believe",
      "p1": "At Faby Services, we believe that financial literacy and access to trustworthy guidance should never be a luxury—they are a fundamental right. Every person and every family deserves to feel confident in their financial decisions, to understand the details, and to face tax season or major life changes with clarity, not confusion.",
      "p2": "Too often, people must navigate complex systems—like taxes, insurance, and legal documentation—without clear direction. We've seen how that uncertainty creates stress, delays, and costly mistakes. Our belief is simple: when people are supported with care and clarity, they make better decisions and improve their quality of life.",
      "p3": "We also believe in preparation—not just for the expected, but for the possible. Life changes quickly. Illness, job changes, growing families, or new businesses bring new financial responsibilities. We help our clients prepare for these transitions with proactive strategies and personalized solutions, ensuring they're never caught by surprise.",
      "p4": "Trust is the foundation of everything we do. We understand that when you hand over your finances, documents, or questions, you're placing great faith in our hands. That trust is never taken for granted. We work hard to earn it, keep it, and reflect it in the way we communicate, plan, and deliver results.",
      "p5": "Ultimately, we believe that dignity, stability, and peace of mind begin with a solid financial foundation. Our role isn't just to process paperwork—it's to strengthen our community by making essential services accessible, understandable, and human. That's the heart of everything we do."
    },
    "founder": {
      "title": "Meet Our Founder",
      "role": "Founder of Faby Services",
      "quote": "\"I am a proud Mexican businesswoman who started this business as a personal dream. Thanks to the trust of my community, that dream has grown into a thriving company committed to offering more than services—we offer a helping hand. From start to finish, I'll be by your side. Tell us what you need and we'll make it happen.\""
    },
    "testimonials": {
      "title": "What Our Clients Say",
      "p1": "At Faby Services, we measure success not just in numbers or transactions, but in the confidence and relief our clients feel as they walk out the door. Our clients come to us seeking answers, guidance, and clarity—and what they take away is confidence, empowerment, and peace of mind.",
      "p2": "We've had the honor of working with people facing complex tax situations, small business owners launching new ventures, and families seeking a more secure future. No matter the challenge, our commitment remains the same: to listen carefully, act with integrity, and offer solutions that truly work.",
      "p3": "Our clients consistently value our transparency and willingness to explain things clearly—without jargon or judgment. For many, it's the first time they feel truly heard and supported in a financial setting. That trust is what drives our work and defines the experience we strive to provide every time.",
      "p4": "Over the years, we've become more than a tax or consulting office—we're a trusted part of our clients' lives. They return year after year, not just for the services, but for the continuity, familiarity, and genuine care they've come to expect. Their referrals, loyalty, and kind words are the best testament to our mission.",
      "p5": "Whether it's a thank-you note or a recommendation to a friend, we don't take praise lightly. Every positive review reflects our team's dedication to putting people first—and reminds us why we started this journey."
    },
    "stats": {
      "title": "Why Choose Us?",
      "p1": "Choosing a financial services partner is about more than credentials or services—it's about trust, consistency, and the assurance of knowing that someone truly has your back. At Faby Services, we take pride in building relationships based on honesty, care, and a deep understanding of our clients' needs.",
      "p2": "From the moment you walk through our doors or call us, you'll experience a different kind of service—one that's personal, not transactional. We take the time to get to know your story, your goals, and the challenges you face. Whether you're preparing your taxes, launching a business, or seeking guidance on insurance, our team is here to make it simple and stress-free.",
      "p3": "What sets us apart is our commitment to clear, practical guidance. We believe in explaining things without jargon and offering solutions without pressure. You'll always know what's happening, why it matters, and what your options are. It's your future—we're just here to help you shape it.",
      "p4": "Our team doesn't just have experience; it's committed. Each member brings not only professional knowledge but also compassion and a sense of responsibility. We approach every situation with care, treating your financial well-being as if it were our own.",
      "p5": "As one of our clients put it: “A well-managed business lets you track every dollar and know exactly when and where to invest it.” We couldn't agree more. That's why we've built a company designed to give you the tools, the vision, and the confidence you need to take control of your financial life—every step of the way."
    }
  },
  "news": {
    "title": "Latest News",
    "loading": "Loading…",
    "empty": "No news available.",
    "readMore": "Read more",
    "notFound": "Article not found.",
    "publishedOn": "Published on",
    "backToNews": "Back to News"
  },
  "openEnrollment": {
    "meta": {
      "titlePrefix": "Open Enrollment",
      "titleSuffix": "Insurance & Bookkeeping"
    },
    "hero": {
      "heading": "Open Enrollment",
      "tagline": "Enroll with Confidence",
      "introPrefix": "Open Enrollment for",
      "introSuffix": "is here. We'll help you choose from the best health insurance plans on the market.",
      "ready": "Ready to enroll?"
    },
    "list": {
      "call": "Call us at (424) 249-0927 or (424) 426-9893",
      "form": "Or fill out our online contact form, and we'll call you whenever it's convenient for you.",
      "guidance": "Get expert guidance at every step of the process.",
      "coverage": "We'll find the right coverage for you."
    },
    "form": {
      "name": "Full Name",
      "phone": "Phone Number",
      "subject": "Subject",
      "subjectPlaceholder": "Select a topic",
      "callback": "Preferred Callback Date and Time",
      "message": "Message",
      "messagePlaceholder": "Tell us about your case or situation...",
      "submit": "Send",
      "reset": "Clear Form"
    },
    "subjects": {
      "bookkeeping": "Bookkeeping",
      "trainingCourses": "Training Courses",
      "taxes": "Taxes",
      "businessConsulting": "Business Consulting Services"
    },
    "countries": {
      "spain": "Spain",
      "mexico": "Mexico",
      "panama": "Panama",
      "peru": "Peru",
      "unitedStates": "United States"
    }
  },
  "reviews": {
    "pageTitle": "Reviews | Faby Services Insurance and Accounting",
    "heading": "Reviews",
    "intro": "Share your experience with Faby Services. Log in or create an account to post and manage your reviews.",
    "login": "Log in",
    "createAccount": "Create account",
    "logout": "Log out",
    "email": "Email",
    "password": "Password",
    "noAccountPrompt": "Don't have an account?",
    "hasAccountPrompt": "Already have an account?",
    "fullName": "Full name",
    "fullNamePlaceholder": "E.g.: John Smith",
    "rating": "Rating",
    "rating5": "5 - Excellent",
    "rating4": "4 - Very good",
    "rating3": "3 - Good",
    "rating2": "2 - Fair",
    "rating1": "1 - Needs improvement",
    "message": "Message",
    "messagePlaceholder": "Tell us about your experience...",
    "postReview": "Post review",
    "updateReview": "Update review",
    "clearForm": "Clear form",
    "edit": "Edit",
    "delete": "Delete",
    "loadMore": "Load more",
    "loading": "Loading reviews…",
    "empty": "No reviews yet.",
    "anonymousUser": "User",
    "errors": {
      "load": "Could not load the reviews.",
      "register": "Could not create the account.",
      "login": "Could not log in.",
      "create": "Could not submit your review.",
      "update": "Could not update your review.",
      "delete": "Could not delete your review."
    }
  },
  "services": {
    "meta": {
      "title": "Services | Faby Services Insurance and Accounting"
    },
    "title": "Explore Our Services",
    "items": {
      "healthInsurance": {
        "title": "Health Insurance",
        "description": "Protect yourself and your loved ones. We offer a full range of coverage options through Covered California and other trusted providers."
      },
      "taxes": {
        "title": "Tax Services",
        "description": "Whether you file personal or corporate taxes, our experienced advisors ensure accurate, compliant, and on-time filings."
      },
      "accounting": {
        "title": "Accounting",
        "description": "Let us handle the bookkeeping, payroll, accounts receivable/payable, and tax records—so you can focus on running your business."
      },
      "notary": {
        "title": "Notary Public",
        "description": "We offer reliable and fast notary services for all types of legal and business documents. We guarantee accuracy, confidentiality, and compliance with current state requirements."
      },
      "training": {
        "title": "Training Courses",
        "description": "Stay up to date with the latest in federal and tax laws. No prior experience required—just the desire to learn and grow."
      }
    },
    "cta": "For expert help and real results for your business—let's get started today."
  },
  "taxSeason": {
    "meta": {
      "titlePrefix": "Tax Season"
    },
    "hero": {
      "headingPrefix": "Tax Season",
      "tagline": "Tax Preparation You Can Trust",
      "introPrefix": "The",
      "introSuffix": "Tax Season is underway. Share your basic details and we'll get in touch to help you file correctly—including extensions through October 15, if applicable."
    },
    "form": {
      "taxpayerName": "Taxpayer's full name",
      "taxpayerDob": "Taxpayer's date of birth",
      "taxpayerPhone": "Taxpayer's phone",
      "spouseName": "Spouse's name (optional)",
      "spouseDob": "Spouse's date of birth (optional)",
      "spousePhone": "Spouse's phone (optional)",
      "optionalPlaceholder": "(Optional)",
      "dependentsCount": "Number of dependents",
      "dependentsDobHeading": "Dependents' dates of birth",
      "dependentLabelPrefix": "Dependent",
      "dependentLabelSuffix": "— Date of birth",
      "message": "Message",
      "messagePlaceholder": "Tell us about your case or situation...",
      "submit": "Send",
      "reset": "Clear Form"
    },
    "countries": {
      "spain": "Spain",
      "mexico": "Mexico",
      "panama": "Panama",
      "peru": "Peru",
      "usa": "United States"
    },
    "email": {
      "subjectPrefix": "Inquiry: Tax Season",
      "bodyIntroPrefix": "New Tax Season request for",
      "taxpayerHeading": "Taxpayer",
      "spouseHeading": "Spouse (optional)",
      "dependentsHeading": "Dependents",
      "fullNameLabel": "Full name",
      "nameLabel": "Name",
      "dobLabel": "Date of birth",
      "phoneLabel": "Phone",
      "dependentsCountLabel": "Number of dependents",
      "dependentLine": "Dependent",
      "noDate": "(no date)",
      "messageLabel": "Message",
      "noMessage": "(no message)"
    }
  }
};
