// Spanish (default) dictionary — generated by merging per-page fragments.
// Keys mirror the other language exactly.
export const es = {
  "nav": {
    "home": "Inicio",
    "services": "Servicios",
    "contact": "Contacto",
    "appointments": "Citas",
    "openEnrollment": "Inscripción Abierta",
    "taxSeason": "Temporada de Impuestos",
    "news": "Noticias",
    "reviews": "Reseñas",
    "switchToEnglish": "Cambiar a inglés",
    "toggleTheme": "Cambiar modo claro/oscuro",
    "toggleNav": "Abrir/cerrar navegación"
  },
  "footer": {
    "adminAccess": "Acceso de administrador",
    "call": "Llamar",
    "email": "Correo electrónico",
    "company": "Faby Services Seguros y Contabilidad",
    "designedBy": "Diseñado por"
  },
  "appointments": {
    "meta": {
      "title": "Citas | Faby Services Seguros y Contabilidad"
    },
    "heading": "Citas",
    "intro": "Envíe su solicitud y nos pondremos en contacto para confirmar la fecha y hora.",
    "form": {
      "name": "Nombre Completo",
      "phone": "Teléfono",
      "preferredDateTime": "Fecha y hora preferidas",
      "message": "Mensaje",
      "messagePlaceholder": "Cuéntenos qué tipo de servicio necesita...",
      "submit": "Enviar",
      "reset": "Borrar Formulario"
    },
    "countries": {
      "us": "Estados Unidos",
      "mx": "México",
      "sv": "El Salvador",
      "ni": "Nicaragua",
      "cr": "Costa Rica",
      "pa": "Panamá",
      "co": "Colombia",
      "es": "España"
    },
    "email": {
      "subject": "Solicitud de Cita",
      "intro": "Nueva solicitud de cita:",
      "name": "Nombre",
      "phone": "Teléfono",
      "preferred": "Fecha/Hora preferida",
      "notSpecified": "(no especificado)",
      "message": "Mensaje",
      "noMessage": "(sin mensaje)"
    }
  },
  "contact": {
    "meta": {
      "title": "Contacto | Faby Services Seguros y Contabilidad"
    },
    "heading": "Contáctenos",
    "intro": "¿Tiene preguntas? Estamos aquí para ayudarle.",
    "details": {
      "phoneLabel": "Teléfono:",
      "emailLabel": "Correo electrónico:",
      "locationLabel": "Ubicación:"
    },
    "cta": "¿Prefiere hablar en persona? Llámenos o visítenos durante el horario de atención.",
    "mapAria": "Abrir mapas"
  },
  "home": {
    "meta": {
      "title": "Inicio | Faby Services"
    },
    "hero": {
      "title": "Servicios Confiables de Impuestos y Consultoría Empresarial",
      "p1": "En Faby Services, ayudamos a individuos, familias y pequeñas empresas a tomar el control de sus finanzas con claridad, confianza y compasión. Entendemos que manejar impuestos, seguros y preparación de documentos puede ser abrumador—especialmente cuando intenta hacerlo por su cuenta. Por eso hemos construido nuestros servicios en torno a una idea simple: apoyo personalizado y honesto en el que puede confiar.",
      "p2": "Nos acercamos a cada cliente con cuidado e intención. Ya sea que esté presentando impuestos por primera vez, asegurando un plan de salud para su familia o administrando las finanzas de su pequeña empresa, escuchamos atentamente sus necesidades y lo guiamos en cada detalle. Sin jerga confusa. Sin explicaciones apresuradas. Solo orientación clara y práctica adaptada a su situación.",
      "p3": "Nuestro equipo está profundamente arraigado en la comunidad a la que servimos. Muchos de nuestros clientes llegan por recomendaciones—de vecinos, amigos y familiares que confían en nosotros para ofrecer resultados. Tomamos esa confianza muy en serio. Por eso hacemos todo lo posible para garantizar que cada formulario sea preciso, cada fecha límite se cumpla y cada pregunta reciba una respuesta reflexiva.",
      "p4": "Más allá del papeleo, estamos aquí para abogar por su bienestar financiero. Nos mantenemos al día con los cambios en las leyes tributarias, las opciones de cobertura médica y los requisitos de cumplimiento, para que usted no tenga que hacerlo. Nuestro objetivo es asegurarnos de que no solo cumpla con sus obligaciones, sino que también aproveche las oportunidades—ahorrando dinero donde pueda y protegiendo lo que más importa.",
      "p5": "Cuando trabaja con Faby Services, no solo contrata a un preparador de impuestos o a un especialista en seguros. Está ganando un socio comprometido con su estabilidad y éxito a largo plazo. Sea cual sea la etapa de la vida en la que se encuentre o los desafíos que enfrente—estamos aquí para apoyarlo en cada paso del camino."
    },
    "mission": {
      "title": "Empoderando Sus Finanzas, Asegurando Su Futuro",
      "p1": "En Faby Services, nos especializamos en brindar apoyo claro y confiable en una variedad de servicios financieros y administrativos, incluyendo asesoría contable, preparación de impuestos y procesamiento de documentos oficiales. Ya sea que sea un individuo planificando el próximo año o una pequeña empresa enfrentando obligaciones complejas, ofrecemos la experiencia y estructura necesarias para avanzar con confianza.",
      "p2": "Nuestro enfoque está basado en la simplicidad y la integridad. Creemos que todos merecen acceso a una planificación financiera sólida—sin intimidación, confusión ni tarifas ocultas. Por eso nos tomamos el tiempo para explicarle sus opciones, ayudarle a tomar decisiones informadas y garantizar que sus documentos sean precisos y cumplan con los requisitos en cada paso del proceso.",
      "p3": "Sabemos que el estrés financiero no solo afecta su bolsillo—también impacta su tranquilidad, su capacidad de planificar el futuro y el bienestar de su familia. Nuestra misión es eliminar ese estrés convirtiéndonos en un socio confiable y con conocimiento en quien pueda confiar año tras año. Ya sea temporada de impuestos, inscripción abierta o tiempo de registrar un negocio, estamos aquí para guiarlo.",
      "p4": "La cobertura médica es otro pilar de nuestro apoyo. Muchos clientes llegan a nosotros sin saber por dónde empezar o abrumados por el proceso de inscripción. Simplificamos ese camino, ayudándole a encontrar y asegurar el mejor seguro posible según sus circunstancias. Porque la seguridad financiera no se trata solo de números—incluye la tranquilidad de saber que su salud y su futuro están protegidos.",
      "p5": "En Faby Services, el empoderamiento no es solo una palabra de moda—es nuestro compromiso. Estamos aquí para ayudarle a tomar el control de sus finanzas, comprender sus derechos y responsabilidades, y dar pasos seguros hacia un futuro más estable. Sin importar su origen o situación, lo recibimos con respeto, claridad y atención genuina."
    },
    "beliefs": {
      "title": "En Qué Creemos",
      "p1": "En Faby Services creemos que la educación financiera y el acceso a orientación confiable nunca deben ser un lujo—son un derecho fundamental. Cada persona y cada familia merecen sentirse seguras en sus decisiones financieras, entender los detalles y enfrentar la temporada de impuestos o los cambios importantes de la vida con claridad, no con confusión.",
      "p2": "Con demasiada frecuencia, las personas deben navegar sistemas complejos—como impuestos, seguros y documentación legal—sin una dirección clara. Hemos visto cómo esa incertidumbre genera estrés, retrasos y errores costosos. Nuestra creencia es simple: cuando las personas reciben apoyo con cuidado y claridad, toman mejores decisiones y mejoran su calidad de vida.",
      "p3": "También creemos en la preparación—no solo para lo esperado, sino para lo posible. La vida cambia rápidamente. Enfermedades, cambios de trabajo, familias en crecimiento o nuevos negocios traen nuevas responsabilidades financieras. Ayudamos a nuestros clientes a prepararse para estas transiciones con estrategias proactivas y soluciones personalizadas, asegurando que nunca los tomen por sorpresa.",
      "p4": "La confianza es la base de todo lo que hacemos. Entendemos que cuando nos entrega sus finanzas, documentos o preguntas, está depositando una gran fe en nuestras manos. Esa confianza nunca se da por sentada. Trabajamos arduamente para ganarla, mantenerla y reflejarla en la forma en que comunicamos, planificamos y entregamos resultados.",
      "p5": "En última instancia, creemos que la dignidad, la estabilidad y la tranquilidad comienzan con una base financiera sólida. Nuestro papel no es solo procesar papeleo—es fortalecer a nuestra comunidad haciendo que los servicios esenciales sean accesibles, comprensibles y humanos. Ese es el corazón de todo lo que hacemos."
    },
    "founder": {
      "title": "Conozca a Nuestra Fundadora",
      "role": "Fundadora de Faby Services",
      "quote": "\"Soy una orgullosa empresaria mexicana que inició este negocio como un sueño personal. Gracias a la confianza de mi comunidad, ese sueño ha crecido hasta convertirse en una empresa próspera comprometida con ofrecer más que servicios—ofrecemos una mano amiga. De principio a fin, estaré a su lado. Cuéntenos lo que necesita y lo haremos realidad.\""
    },
    "testimonials": {
      "title": "Lo Que Dicen Nuestros Clientes",
      "p1": "En Faby Services, medimos el éxito no solo en números o transacciones, sino en la confianza y alivio que sienten nuestros clientes al salir por la puerta. Nuestros clientes nos buscan en busca de respuestas, orientación y claridad—y lo que se llevan es confianza, empoderamiento y tranquilidad.",
      "p2": "Hemos tenido el honor de trabajar con personas enfrentando situaciones fiscales complejas, dueños de pequeñas empresas lanzando nuevos proyectos y familias que buscan un futuro más seguro. Sin importar el desafío, nuestro compromiso sigue siendo el mismo: escuchar con atención, actuar con integridad y ofrecer soluciones que realmente funcionen.",
      "p3": "Nuestros clientes valoran constantemente nuestra transparencia y disposición para explicar las cosas con claridad—sin jerga ni juicios. Para muchos, es la primera vez que se sienten verdaderamente escuchados y apoyados en un entorno financiero. Esa confianza es lo que impulsa nuestro trabajo y define la experiencia que buscamos brindar cada vez.",
      "p4": "A lo largo de los años, nos hemos convertido en más que una oficina de impuestos o consultoría—somos una parte confiable de la vida de nuestros clientes. Regresan año tras año, no solo por los servicios, sino por la continuidad, familiaridad y atención genuina que han llegado a esperar. Sus recomendaciones, lealtad y palabras amables son el mejor testimonio de nuestra misión.",
      "p5": "Ya sea una nota de agradecimiento o una recomendación a un amigo, no tomamos los elogios a la ligera. Cada reseña positiva refleja la dedicación de nuestro equipo para poner a las personas primero—y nos recuerda por qué comenzamos este camino."
    },
    "stats": {
      "title": "¿Por Qué Elegirnos?",
      "p1": "Elegir un socio de servicios financieros es más que credenciales o servicios—se trata de confianza, consistencia y la seguridad de saber que alguien realmente lo respalda. En Faby Services, nos enorgullece construir relaciones basadas en la honestidad, el cuidado y una profunda comprensión de las necesidades de nuestros clientes.",
      "p2": "Desde el momento en que cruza nuestras puertas o nos llama, experimentará un tipo de servicio diferente—uno personal, no transaccional. Nos tomamos el tiempo para conocer su historia, sus metas y los desafíos que enfrenta. Ya sea preparando sus impuestos, lanzando un negocio o buscando orientación sobre seguros, nuestro equipo está aquí para hacerlo simple y sin estrés.",
      "p3": "Lo que nos distingue es nuestro compromiso con una orientación clara y práctica. Creemos en explicar las cosas sin jerga y ofrecer soluciones sin presión. Siempre sabrá lo que está pasando, por qué importa y cuáles son sus opciones. Es su futuro—nosotros solo estamos aquí para ayudarle a moldearlo.",
      "p4": "Nuestro equipo no solo tiene experiencia; está comprometido. Cada miembro aporta no solo conocimiento profesional sino también compasión y sentido de responsabilidad. Abordamos cada situación con cuidado, tratando su bienestar financiero como si fuera el nuestro.",
      "p5": "Como dijo uno de nuestros clientes: “Un negocio bien administrado le permite rastrear cada dólar y saber exactamente cuándo y dónde invertirlo.” No podríamos estar más de acuerdo. Por eso hemos construido una empresa diseñada para darle las herramientas, la visión y la confianza necesarias para tomar el control de su vida financiera—en cada paso del camino."
    }
  },
  "news": {
    "title": "Últimas Noticias",
    "loading": "Cargando…",
    "empty": "No hay noticias disponibles.",
    "readMore": "Leer más",
    "notFound": "Noticia no encontrada.",
    "publishedOn": "Publicado el",
    "backToNews": "Volver a Noticias"
  },
  "openEnrollment": {
    "meta": {
      "titlePrefix": "Inscripción Abierta",
      "titleSuffix": "Seguros y Contabilidad"
    },
    "hero": {
      "heading": "Inscripción Abierta",
      "tagline": "Inscríbase con Confianza",
      "introPrefix": "La Inscripción Abierta",
      "introSuffix": "ya está aquí. Le ayudaremos a seleccionar entre los mejores planes de seguro médico del mercado.",
      "ready": "¿Listo para inscribirse?"
    },
    "list": {
      "call": "Llámenos al (424) 249-0927 o (424) 426-9893",
      "form": "O complete nuestro formulario de contacto en línea, y lo llamaremos cuando le sea conveniente.",
      "guidance": "Reciba orientación experta en cada paso del proceso.",
      "coverage": "Encontraremos la cobertura adecuada para usted."
    },
    "form": {
      "name": "Nombre Completo",
      "phone": "Número de Teléfono",
      "subject": "Asunto",
      "subjectPlaceholder": "Seleccione un tema",
      "callback": "Fecha y Hora para Devolver la Llamada",
      "message": "Mensaje",
      "messagePlaceholder": "Cuéntenos sobre su caso o situación...",
      "submit": "Enviar",
      "reset": "Borrar Formulario"
    },
    "subjects": {
      "bookkeeping": "Contabilidad",
      "trainingCourses": "Cursos de Capacitación",
      "taxes": "Impuestos",
      "businessConsulting": "Servicios de Consultoría Empresarial"
    },
    "countries": {
      "spain": "España",
      "mexico": "México",
      "panama": "Panamá",
      "peru": "Perú",
      "unitedStates": "Estados Unidos"
    }
  },
  "reviews": {
    "pageTitle": "Reseñas | Faby Services Seguros y Contabilidad",
    "heading": "Reseñas",
    "intro": "Comparte tu experiencia con Faby Services. Inicia sesión o crea una cuenta para publicar y gestionar tus reseñas.",
    "login": "Iniciar sesión",
    "createAccount": "Crear cuenta",
    "logout": "Cerrar sesión",
    "email": "Correo electrónico",
    "password": "Contraseña",
    "noAccountPrompt": "¿No tienes cuenta?",
    "hasAccountPrompt": "¿Ya tienes cuenta?",
    "fullName": "Nombre completo",
    "fullNamePlaceholder": "Ej.: Juan Pérez",
    "rating": "Calificación",
    "rating5": "5 - Excelente",
    "rating4": "4 - Muy bueno",
    "rating3": "3 - Bueno",
    "rating2": "2 - Regular",
    "rating1": "1 - Necesita mejorar",
    "message": "Mensaje",
    "messagePlaceholder": "Cuéntenos sobre su experiencia...",
    "postReview": "Publicar reseña",
    "updateReview": "Actualizar reseña",
    "clearForm": "Borrar Formulario",
    "edit": "Editar",
    "delete": "Eliminar",
    "loadMore": "Cargar más",
    "loading": "Cargando reseñas…",
    "empty": "Aún no hay reseñas.",
    "anonymousUser": "Usuario",
    "errors": {
      "load": "No se pudieron cargar las reseñas.",
      "register": "No se pudo crear la cuenta.",
      "login": "No se pudo iniciar sesión.",
      "create": "No se pudo enviar su reseña.",
      "update": "No se pudo actualizar su reseña.",
      "delete": "No se pudo eliminar su reseña."
    }
  },
  "services": {
    "meta": {
      "title": "Servicios | Faby Services Seguros y Contabilidad"
    },
    "title": "Explore Nuestros Servicios",
    "items": {
      "healthInsurance": {
        "title": "Seguro Médico",
        "description": "Proteja a usted y a sus seres queridos. Ofrecemos una gama completa de opciones de cobertura a través de Covered California y otros proveedores confiables."
      },
      "taxes": {
        "title": "Servicios de Impuestos",
        "description": "Ya sea que presente impuestos personales o corporativos, nuestros asesores experimentados garantizan presentaciones precisas, cumplidas y a tiempo."
      },
      "accounting": {
        "title": "Contabilidad",
        "description": "Permítanos encargarnos de la contabilidad, nómina, cuentas por cobrar/pagar y registros fiscales—para que usted pueda concentrarse en administrar su negocio."
      },
      "notary": {
        "title": "Notary Public",
        "description": "Ofrecemos servicios notariales confiables y rápidos para todo tipo de documentos legales y comerciales. Garantizamos precisión, confidencialidad y cumplimiento con los requisitos estatales vigentes."
      },
      "training": {
        "title": "Cursos de Capacitación",
        "description": "Manténgase actualizado con lo más reciente en leyes federales y fiscales. No se requiere experiencia previa—solo el deseo de aprender y crecer."
      }
    },
    "cta": "Para obtener ayuda experta y resultados reales para su negocio—comencemos hoy."
  },
  "taxSeason": {
    "meta": {
      "titlePrefix": "Temporada de Impuestos"
    },
    "hero": {
      "headingPrefix": "Temporada de Impuestos",
      "tagline": "Preparación de Impuestos con Confianza",
      "introPrefix": "La Temporada de Impuestos",
      "introSuffix": "está en curso. Comparta sus datos básicos y nos pondremos en contacto para ayudarle a presentar correctamente—incluyendo extensiones hasta el 15 de octubre, si corresponde."
    },
    "form": {
      "taxpayerName": "Nombre completo del contribuyente",
      "taxpayerDob": "Fecha de nacimiento del contribuyente",
      "taxpayerPhone": "Teléfono del contribuyente",
      "spouseName": "Nombre del esposo(a) (opcional)",
      "spouseDob": "Fecha de nacimiento del esposo(a) (opcional)",
      "spousePhone": "Teléfono del esposo(a) (opcional)",
      "optionalPlaceholder": "(Opcional)",
      "dependentsCount": "Número de dependientes",
      "dependentsDobHeading": "Fechas de nacimiento de dependientes",
      "dependentLabelPrefix": "Dependiente",
      "dependentLabelSuffix": "— Fecha de nacimiento",
      "message": "Mensaje",
      "messagePlaceholder": "Cuéntenos sobre su caso o situación...",
      "submit": "Enviar",
      "reset": "Borrar Formulario"
    },
    "countries": {
      "spain": "España",
      "mexico": "México",
      "panama": "Panamá",
      "peru": "Perú",
      "usa": "Estados Unidos"
    },
    "email": {
      "subjectPrefix": "Consulta: Temporada de Impuestos",
      "bodyIntroPrefix": "Nueva solicitud de Temporada de Impuestos",
      "taxpayerHeading": "Contribuyente",
      "spouseHeading": "Esposo(a) (opcional)",
      "dependentsHeading": "Dependientes",
      "fullNameLabel": "Nombre completo",
      "nameLabel": "Nombre",
      "dobLabel": "Fecha de nacimiento",
      "phoneLabel": "Teléfono",
      "dependentsCountLabel": "Número de dependientes",
      "dependentLine": "Dependiente",
      "noDate": "(sin fecha)",
      "messageLabel": "Mensaje",
      "noMessage": "(sin mensaje)"
    }
  }
};
